//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int id { get; set; }
        public Nullable<System.DateTime> docDate { get; set; }
        public string accountTitle { get; set; }
        public int accountId { get; set; }
        public string narration { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int TranstypeId { get; set; }
        public Nullable<int> vchrStatus { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
    }
}
