//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_transaction
    {
        public int accounts_transaction_id { get; set; }
        public int refId { get; set; }
        public int orders_id { get; set; }
        public int customers_id { get; set; }
        public string details { get; set; }
        public Nullable<decimal> trans_db { get; set; }
        public Nullable<decimal> trans_cr { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> chqNo { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> chq_ok { get; set; }
        public Nullable<System.DateTime> chq_date { get; set; }
    }
}
