//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public long ID { get; set; }
        public Nullable<long> BankID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string AccountNo { get; set; }
        public string AccountTitle { get; set; }
        public string BranchManager { get; set; }
        public string BranchManagerContact { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string SecContactPerson { get; set; }
        public string SecContactNo { get; set; }
        public string LandLineNo { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
    }
}
