//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilty()
        {
            this.BiltyDetails = new HashSet<BiltyDetail>();
            this.Challans = new HashSet<Challan>();
            this.CompactCheckBills = new HashSet<CompactCheckBill>();
            this.CompactCheckBilties = new HashSet<CompactCheckBilty>();
            this.PartialBilties = new HashSet<PartialBilty>();
        }
    
        public long ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public long OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public long Reciever { get; set; }
        public long BillTo { get; set; }
        public string ExternalVno { get; set; }
        public Nullable<long> Sender { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public long OwnCompany { get; set; }
        public string CustomerType { get; set; }
        public long PickLocation { get; set; }
        public Nullable<double> WeightQTYTotal { get; set; }
        public Nullable<double> TotalFreight { get; set; }
        public Nullable<double> OrderDetailsTotalQTY { get; set; }
        public Nullable<double> OrderDetailsTotalWeight { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public string ExternalVehicleNo { get; set; }
        public Nullable<double> TotalAdditionalFreight { get; set; }
        public Nullable<double> TotalWeighbridge { get; set; }
        public Nullable<double> Labour { get; set; }
        public string Remarks { get; set; }
    
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual CustomerCompany CustomerCompany1 { get; set; }
        public virtual OwnCompany OwnCompany1 { get; set; }
        public virtual OwnCompany OwnCompany2 { get; set; }
        public virtual PickLocation PickLocation1 { get; set; }
        public virtual PickLocation PickLocation2 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiltyDetail> BiltyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Challan> Challans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompactCheckBill> CompactCheckBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompactCheckBilty> CompactCheckBilties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartialBilty> PartialBilties { get; set; }
    }
}
