//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiltyRole
    {
        public long ID { get; set; }
        public Nullable<long> UserId { get; set; }
        public string BiltyRole1 { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
