//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompactCheckBill
    {
        public long ID { get; set; }
        public Nullable<long> CompactBillID { get; set; }
        public Nullable<long> BiltyID { get; set; }
    
        public virtual Bilty Bilty { get; set; }
        public virtual CompactBill CompactBill { get; set; }
    }
}
