//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompactCheckBilty
    {
        public long ID { get; set; }
        public Nullable<long> CompactChallanID { get; set; }
        public Nullable<long> CompactBiltyID { get; set; }
        public string Type { get; set; }
    
        public virtual Bilty Bilty { get; set; }
        public virtual Challan Challan { get; set; }
    }
}
