//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerProfile()
        {
            this.CustomerProfileDetails = new HashSet<CustomerProfileDetail>();
        }
    
        public long ProfileId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> OwnCompanyId { get; set; }
        public string PaymentTerm { get; set; }
        public string CreditTerm { get; set; }
        public string InvoiceFormat { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> isHide { get; set; }
        public Nullable<bool> IsAdditionalCharges { get; set; }
        public Nullable<bool> IsLaborCharges { get; set; }
    
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProfileDetail> CustomerProfileDetails { get; set; }
    }
}
