//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProfileDetail_Audit
    {
        public long ProfileDetail_AuditID { get; set; }
        public Nullable<long> ProfileDetail { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> LocationFrom { get; set; }
        public Nullable<long> LocationTo { get; set; }
        public string RateType { get; set; }
        public Nullable<long> DoorStepRate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<long> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> WeightPerUnit { get; set; }
        public Nullable<double> AdditionCharges { get; set; }
        public Nullable<double> LabourCharges { get; set; }
        public string AuditDataState { get; set; }
        public string AuditDMLAction { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string UpdateColumns { get; set; }
    }
}
