//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieselExpense
    {
        public long ID { get; set; }
        public Nullable<long> DieselID { get; set; }
        public double DieselLiter { get; set; }
        public Nullable<double> DieselAmount { get; set; }
        public Nullable<double> OtherAmount { get; set; }
        public Nullable<double> OilLiter { get; set; }
        public Nullable<double> OilAmount { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> CashReceived { get; set; }
        public Nullable<double> CashPaid { get; set; }
        public Nullable<long> RegNo { get; set; }
        public Nullable<double> DieselRate { get; set; }
        public Nullable<double> OilRate { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> SerialNo { get; set; }
    
        public virtual Diesel Diesel { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
