//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.UniversalBiltyReceivingInformations = new HashSet<UniversalBiltyReceivingInformation>();
        }
    
        public long EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UploadDocument { get; set; }
        public string CNIC { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public string FatherName { get; set; }
        public string CNICImagePath { get; set; }
        public Nullable<long> OwnGroupID { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string IdentityMark { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> NICIssueDate { get; set; }
        public Nullable<System.DateTime> NICExpiryDate { get; set; }
        public string ContactNo { get; set; }
        public string OtherContactNo { get; set; }
        public string HomeContactNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public string ContactRelation { get; set; }
        public string EmergencyContactName { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual OwnCompany OwnCompany1 { get; set; }
        public virtual OwnGroup OwnGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversalBiltyReceivingInformation> UniversalBiltyReceivingInformations { get; set; }
    }
}
