//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_ACC
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int parent_id { get; set; }
        public int isActive { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public string CODE { get; set; }
        public Nullable<int> LEVEL { get; set; }
    }
}
