//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public long GroupID { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public string Contact { get; set; }
        public string ContactOther { get; set; }
        public string EmailAdd { get; set; }
        public string WebAdd { get; set; }
        public string Address { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> CreatedByUserID { get; set; }
        public Nullable<long> ModifiedByUserID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyAccess { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
