//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LCMEntities : DbContext
    {
        public LCMEntities()
            : base("name=LCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accounts_transaction> accounts_transaction { get; set; }
        public virtual DbSet<BiltyRole> BiltyRoles { get; set; }
        public virtual DbSet<ContactNoType> ContactNoTypes { get; set; }
        public virtual DbSet<CurrencyType> CurrencyTypes { get; set; }
        public virtual DbSet<CustomerCompany> CustomerCompanies { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<DateType> DateTypes { get; set; }
        public virtual DbSet<GM_ACC> GM_ACC { get; set; }
        public virtual DbSet<M_FLAG> M_FLAG { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NavMenu> NavMenus { get; set; }
        public virtual DbSet<NoType> NoTypes { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orders_products> orders_products { get; set; }
        public virtual DbSet<OwnCompany> OwnCompanies { get; set; }
        public virtual DbSet<OwnGroup> OwnGroups { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SecondLevelMenu> SecondLevelMenus { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<SoftwareSetup> SoftwareSetups { get; set; }
        public virtual DbSet<SubcriptionModule> SubcriptionModules { get; set; }
        public virtual DbSet<Subcription> Subcriptions { get; set; }
        public virtual DbSet<TEST> TESTs { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserAssignedCompany> UserAssignedCompanies { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorType> VendorTypes { get; set; }
    
        [DbFunction("LCMEntities", "GetAccountBalance")]
        public virtual IQueryable<GetAccountBalance_Result> GetAccountBalance(Nullable<int> accountId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAccountBalance_Result>("[LCMEntities].[GetAccountBalance](@accountId)", accountIdParameter);
        }
    
        [DbFunction("LCMEntities", "GetCustomersByAcc")]
        public virtual IQueryable<GetCustomersByAcc_Result> GetCustomersByAcc(Nullable<int> accountId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetCustomersByAcc_Result>("[LCMEntities].[GetCustomersByAcc](@accountId)", accountIdParameter);
        }
    
        [DbFunction("LCMEntities", "CUST_LEDGER")]
        public virtual IQueryable<CUST_LEDGER_Result> CUST_LEDGER(Nullable<int> customerId, Nullable<System.DateTime> frmDt, Nullable<System.DateTime> toDt, Nullable<int> typeId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("customerId", customerId) :
                new ObjectParameter("customerId", typeof(int));
    
            var frmDtParameter = frmDt.HasValue ?
                new ObjectParameter("frmDt", frmDt) :
                new ObjectParameter("frmDt", typeof(System.DateTime));
    
            var toDtParameter = toDt.HasValue ?
                new ObjectParameter("toDt", toDt) :
                new ObjectParameter("toDt", typeof(System.DateTime));
    
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("typeId", typeId) :
                new ObjectParameter("typeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CUST_LEDGER_Result>("[LCMEntities].[CUST_LEDGER](@customerId, @frmDt, @toDt, @typeId)", customerIdParameter, frmDtParameter, toDtParameter, typeIdParameter);
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AssignDriver> AssignDrivers { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BillChild> BillChilds { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Bilty> Bilties { get; set; }
        public virtual DbSet<BiltyDetail> BiltyDetails { get; set; }
        public virtual DbSet<BiltyRole> BiltyRoles { get; set; }
        public virtual DbSet<Broker> Brokers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Challan> Challans { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompactBill> CompactBills { get; set; }
        public virtual DbSet<CompactCheckBill> CompactCheckBills { get; set; }
        public virtual DbSet<CompactCheckBilty> CompactCheckBilties { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContactNoType> ContactNoTypes { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<ContainerType> ContainerTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CurrencyType> CurrencyTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerCompany> CustomerCompanies { get; set; }
        public virtual DbSet<CustomerDepartment> CustomerDepartments { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }
        public virtual DbSet<CustomerProfileDetail> CustomerProfileDetails { get; set; }
        public virtual DbSet<CustomerProfileLM> CustomerProfileLMS { get; set; }
        public virtual DbSet<customer1> customers1 { get; set; }
        public virtual DbSet<Damage> Damages { get; set; }
        public virtual DbSet<DamageType> DamageTypes { get; set; }
        public virtual DbSet<DateType> DateTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentPerson> DepartmentPersons { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Diesel> Diesels { get; set; }
        public virtual DbSet<DieselExpense> DieselExpenses { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverMedical> DriverMedicals { get; set; }
        public virtual DbSet<DriverType> DriverTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpensesType> ExpensesTypes { get; set; }
        public virtual DbSet<FillingStation> FillingStations { get; set; }
        public virtual DbSet<Gener> Geners { get; set; }
        public virtual DbSet<GM_ACC> GM_ACC { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LocalDropProduct> LocalDropProducts { get; set; }
        public virtual DbSet<LocalDropUniversalBilty> LocalDropUniversalBilties { get; set; }
        public virtual DbSet<LocalPickProduct> LocalPickProducts { get; set; }
        public virtual DbSet<LocalPickUniversalBilty> LocalPickUniversalBilties { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<M_FLAG> M_FLAG { get; set; }
        public virtual DbSet<MaintenanceType> MaintenanceTypes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<NavMenu> NavMenus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NoType> NoTypes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orders_products> orders_products { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OwnCompany> OwnCompanies { get; set; }
        public virtual DbSet<OwnGroup> OwnGroups { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<ParchoonBill> ParchoonBills { get; set; }
        public virtual DbSet<ParchoonBiltyChallan> ParchoonBiltyChallans { get; set; }
        public virtual DbSet<ParchoonBiltyCheck> ParchoonBiltyChecks { get; set; }
        public virtual DbSet<ParchoonCheckBill> ParchoonCheckBills { get; set; }
        public virtual DbSet<PartialBilty> PartialBilties { get; set; }
        public virtual DbSet<PartialBiltyDetail> PartialBiltyDetails { get; set; }
        public virtual DbSet<PickDropLocation> PickDropLocations { get; set; }
        public virtual DbSet<PickLocation> PickLocations { get; set; }
        public virtual DbSet<PrincipleCompany> PrincipleCompanies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductBroker> ProductBrokers { get; set; }
        public virtual DbSet<product1> products1 { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RateList> RateLists { get; set; }
        public virtual DbSet<Receiver> Receivers { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenueType> RevenueTypes { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SaleOrdeDestination> SaleOrdeDestinations { get; set; }
        public virtual DbSet<SaleOrder> SaleOrders { get; set; }
        public virtual DbSet<SaleOrderChild> SaleOrderChilds { get; set; }
        public virtual DbSet<SaleOrderDieselExpense> SaleOrderDieselExpenses { get; set; }
        public virtual DbSet<SaleOrderExpens> SaleOrderExpenses { get; set; }
        public virtual DbSet<SalesOrderChildDestination> SalesOrderChildDestinations { get; set; }
        public virtual DbSet<SalesOrderChildDieselExpens> SalesOrderChildDieselExpenses { get; set; }
        public virtual DbSet<SalesOrderChildExpens> SalesOrderChildExpenses { get; set; }
        public virtual DbSet<SecondLevelMenu> SecondLevelMenus { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<ShipmentType> ShipmentTypes { get; set; }
        public virtual DbSet<ShippingLine> ShippingLines { get; set; }
        public virtual DbSet<ShippingType> ShippingTypes { get; set; }
        public virtual DbSet<SoftwareSetup> SoftwareSetups { get; set; }
        public virtual DbSet<StandardVehicle> StandardVehicles { get; set; }
        public virtual DbSet<SubcriptionModule> SubcriptionModules { get; set; }
        public virtual DbSet<Subcription> Subcriptions { get; set; }
        public virtual DbSet<TaxRateRegistration> TaxRateRegistrations { get; set; }
        public virtual DbSet<TaxRateTransportation> TaxRateTransportations { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<Trailer> Trailers { get; set; }
        public virtual DbSet<TrailerType> TrailerTypes { get; set; }
        public virtual DbSet<Transporter> Transporters { get; set; }
        public virtual DbSet<UniversalBill> UniversalBills { get; set; }
        public virtual DbSet<UniversalBilty> UniversalBilties { get; set; }
        public virtual DbSet<UniversalBiltyContainerInformation> UniversalBiltyContainerInformations { get; set; }
        public virtual DbSet<UniversalBiltyCustomerInformation> UniversalBiltyCustomerInformations { get; set; }
        public virtual DbSet<UniversalBiltyDamageDetail> UniversalBiltyDamageDetails { get; set; }
        public virtual DbSet<UniversalBiltyDispatchDocument> UniversalBiltyDispatchDocuments { get; set; }
        public virtual DbSet<UniversalBiltyExpenseDetail> UniversalBiltyExpenseDetails { get; set; }
        public virtual DbSet<UniversalBiltyFreightDetail> UniversalBiltyFreightDetails { get; set; }
        public virtual DbSet<UniversalBiltyLocationInformation> UniversalBiltyLocationInformations { get; set; }
        public virtual DbSet<UniversalBiltyProductInformation> UniversalBiltyProductInformations { get; set; }
        public virtual DbSet<UniversalBiltyReceivingDocumentDetail> UniversalBiltyReceivingDocumentDetails { get; set; }
        public virtual DbSet<UniversalBiltyReceivingInformation> UniversalBiltyReceivingInformations { get; set; }
        public virtual DbSet<UniversalBiltyVehicleInformation> UniversalBiltyVehicleInformations { get; set; }
        public virtual DbSet<UniversalBiltyVehicleLoadingReporting> UniversalBiltyVehicleLoadingReportings { get; set; }
        public virtual DbSet<UniversalBiltyVehicleUnLoadingReporting> UniversalBiltyVehicleUnLoadingReportings { get; set; }
        public virtual DbSet<UniversalChallan> UniversalChallans { get; set; }
        public virtual DbSet<UniversalCheckBill> UniversalCheckBills { get; set; }
        public virtual DbSet<UniversalCheckBilty> UniversalCheckBilties { get; set; }
        public virtual DbSet<UniversalContainerDetail> UniversalContainerDetails { get; set; }
        public virtual DbSet<UniversalVehicleDetail> UniversalVehicleDetails { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserAssignedCompany> UserAssignedCompanies { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleDocument> VehicleDocuments { get; set; }
        public virtual DbSet<VehicleExpens> VehicleExpenses { get; set; }
        public virtual DbSet<VehicleMaintenance> VehicleMaintenances { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorType> VendorTypes { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<CustomerProfileDetail_Audit> CustomerProfileDetail_Audit { get; set; }
        public virtual DbSet<ParchoonBilty> ParchoonBilties { get; set; }
        public virtual DbSet<ParchoonBiltyDocumentType> ParchoonBiltyDocumentTypes { get; set; }
        public virtual DbSet<ParchoonBiltyExpense> ParchoonBiltyExpenses { get; set; }
        public virtual DbSet<ParchoonBiltyProduct> ParchoonBiltyProducts { get; set; }
    
        public virtual int GetDataByIdName(string status, string name, Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string code)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(System.DateTime));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDataByIdName", statusParameter, nameParameter, fromdateParameter, todateParameter, codeParameter);
        }
    }
}
