//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalDropProduct
    {
        public long ID { get; set; }
        public Nullable<long> LocalDropID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<double> Qty { get; set; }
        public string Item { get; set; }
        public Nullable<double> TotalItemQty { get; set; }
        public Nullable<double> TotalWeight { get; set; }
    
        public virtual LocalDropUniversalBilty LocalDropUniversalBilty { get; set; }
        public virtual Product Product { get; set; }
    }
}
