//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalPickUniversalBilty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalPickUniversalBilty()
        {
            this.LocalPickProducts = new HashSet<LocalPickProduct>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ConsignerSender { get; set; }
        public Nullable<long> ConsignerReceiver { get; set; }
        public Nullable<long> BillTo { get; set; }
        public Nullable<System.DateTime> LocalPickDate { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<double> FreightExpense { get; set; }
        public Nullable<double> FreightCharged { get; set; }
        public Nullable<long> PickLocationID { get; set; }
        public Nullable<long> DropLocationID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
    
        public virtual CustomerProfileLM CustomerProfileLM { get; set; }
        public virtual CustomerProfileLM CustomerProfileLM1 { get; set; }
        public virtual CustomerProfileLM CustomerProfileLM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalPickProduct> LocalPickProducts { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual PickLocation PickLocation { get; set; }
        public virtual PickLocation PickLocation1 { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
