//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_products
    {
        public int orders_products_id { get; set; }
        public int orders_id { get; set; }
        public int products_id { get; set; }
        public string products_name { get; set; }
        public Nullable<int> products_quantity { get; set; }
        public Nullable<decimal> products_price { get; set; }
        public Nullable<int> scheme { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<decimal> discPer { get; set; }
        public Nullable<decimal> discAmt { get; set; }
        public Nullable<decimal> lineAmount { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
    }
}
