//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long OrderId { get; set; }
        public Nullable<long> WorkOrderID { get; set; }
        public Nullable<long> Reciever { get; set; }
        public Nullable<long> Productbroker { get; set; }
        public Nullable<long> PackageType { get; set; }
        public Nullable<long> Product { get; set; }
        public Nullable<long> Weight { get; set; }
        public string unit { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> TotalWeight { get; set; }
        public string Remarks { get; set; }
    
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual PackageType PackageType1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual ProductBroker ProductBroker1 { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
