//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParchoonBilty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParchoonBilty()
        {
            this.ParchoonBiltyChecks = new HashSet<ParchoonBiltyCheck>();
            this.ParchoonBiltyDocumentTypes = new HashSet<ParchoonBiltyDocumentType>();
            this.ParchoonBiltyExpenses = new HashSet<ParchoonBiltyExpense>();
            this.ParchoonBiltyProducts = new HashSet<ParchoonBiltyProduct>();
            this.ParchoonCheckBills = new HashSet<ParchoonCheckBill>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ShipmentTypeID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> BiltyNo { get; set; }
        public string ManualBiltyNo { get; set; }
        public string DNNo { get; set; }
        public Nullable<long> CustomerCompanyID { get; set; }
        public Nullable<long> VehicleTypeID { get; set; }
        public Nullable<long> BrokerID { get; set; }
        public string CellNo { get; set; }
        public string Status { get; set; }
        public Nullable<double> TotalQty { get; set; }
        public Nullable<double> AdditionalFreight { get; set; }
        public Nullable<double> TotalFreight { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> AdditionalWeight { get; set; }
        public Nullable<double> TotalGrossWeight { get; set; }
        public Nullable<double> TotalExpense { get; set; }
        public Nullable<double> LocalFreight { get; set; }
        public Nullable<double> FreightRs { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public string DeliverType { get; set; }
        public Nullable<long> PickLocationID { get; set; }
        public Nullable<long> DropLocationID { get; set; }
        public Nullable<long> PickStationID { get; set; }
        public Nullable<long> DropStationID { get; set; }
        public string PickAddress { get; set; }
        public string DropAddress { get; set; }
        public Nullable<long> ReceiverID { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual Transporter Transporter { get; set; }
        public virtual Transporter Transporter1 { get; set; }
        public virtual ProductBroker ProductBroker { get; set; }
        public virtual Receiver Receiver { get; set; }
        public virtual ShipmentType ShipmentType { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParchoonBiltyCheck> ParchoonBiltyChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParchoonBiltyDocumentType> ParchoonBiltyDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParchoonBiltyExpense> ParchoonBiltyExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParchoonBiltyProduct> ParchoonBiltyProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParchoonCheckBill> ParchoonCheckBills { get; set; }
    }
}
