//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParchoonBiltyExpense
    {
        public long ID { get; set; }
        public Nullable<long> ParchoonBiltyID { get; set; }
        public Nullable<long> ExpenseTypeID { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual ExpensesType ExpensesType { get; set; }
        public virtual ParchoonBilty ParchoonBilty { get; set; }
    }
}
