//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int products_id { get; set; }
        public string products_model { get; set; }
        public string productDescription { get; set; }
        public string products_name { get; set; }
        public Nullable<decimal> products_msrp { get; set; }
        public Nullable<decimal> products_tp { get; set; }
        public Nullable<decimal> products_scheme { get; set; }
        public Nullable<decimal> products_bonus { get; set; }
        public Nullable<decimal> products_discPer { get; set; }
        public Nullable<decimal> products_discAmt { get; set; }
        public bool isActive { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
    }
}
