//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderChildDestination
    {
        public long ID { get; set; }
        public Nullable<long> SaleOrderChildID { get; set; }
        public string DestinationCode { get; set; }
        public Nullable<long> DestinationLocation { get; set; }
        public Nullable<long> Province { get; set; }
        public Nullable<long> City { get; set; }
        public string GSTType { get; set; }
        public Nullable<long> TaxRateTransportationID { get; set; }
        public Nullable<long> TaxRateRegistrationID { get; set; }
        public Nullable<long> Product { get; set; }
        public Nullable<long> ProductQty { get; set; }
        public Nullable<double> Frieght { get; set; }
        public Nullable<int> ShortageQty { get; set; }
        public string Shortage { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> OwnCompanyId { get; set; }
    
        public virtual PickLocation PickLocation { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual SaleOrderChild SaleOrderChild { get; set; }
    }
}
