//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderChildExpens
    {
        public long ID { get; set; }
        public Nullable<long> OwnCompanyId { get; set; }
        public Nullable<long> SaleOrderChildID { get; set; }
        public Nullable<long> Instrument { get; set; }
        public Nullable<long> ExpenseTypeId { get; set; }
        public string RecievedBy { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<long> BankBranchId { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual ExpensesType ExpensesType { get; set; }
        public virtual SaleOrderChild SaleOrderChild { get; set; }
    }
}
