//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrder()
        {
            this.SaleOrdeDestinations = new HashSet<SaleOrdeDestination>();
            this.SaleOrderChilds = new HashSet<SaleOrderChild>();
            this.SaleOrderDieselExpenses = new HashSet<SaleOrderDieselExpense>();
            this.SaleOrderExpenses = new HashSet<SaleOrderExpens>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CustomerCompanyId { get; set; }
        public Nullable<long> SaleOrderNo { get; set; }
        public Nullable<long> InvoiceNo { get; set; }
        public Nullable<long> QueNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<long> OwnCompanyId { get; set; }
        public Nullable<long> ShipmentTypeId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> AreaIdForLoadingPoint { get; set; }
        public Nullable<long> AreaIdForDestinationPoint { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<System.DateTime> DecantationDate { get; set; }
        public string TokenNumber { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public string LoadingCode { get; set; }
        public Nullable<long> LoadingLocationId { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string GSTType { get; set; }
        public Nullable<long> TaxID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ManualNo { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual PickLocation PickLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrdeDestination> SaleOrdeDestinations { get; set; }
        public virtual ShipmentType ShipmentType { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderChild> SaleOrderChilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderDieselExpense> SaleOrderDieselExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderExpens> SaleOrderExpenses { get; set; }
    }
}
