//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingLine
    {
        public long ShippingLineID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<long> PrimaryContact { get; set; }
        public Nullable<long> SecondaryContact { get; set; }
        public Nullable<long> LandLine { get; set; }
        public string EmailAddress { get; set; }
        public string WebSite { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> CreatedById { get; set; }
        public Nullable<long> ModifiedByID { get; set; }
        public Nullable<double> LiftOffLiftOnCharges { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
