//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareSetup
    {
        public long ID { get; set; }
        public Nullable<long> CurrencyTypeID { get; set; }
        public Nullable<long> DateTypeID { get; set; }
        public Nullable<long> ContactNoTypeID { get; set; }
        public Nullable<long> NoTypeID { get; set; }
        public string Logo { get; set; }
    
        public virtual ContactNoType ContactNoType { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual DateType DateType { get; set; }
        public virtual NoType NoType { get; set; }
    }
}
