//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRateTransportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxRateTransportation()
        {
            this.SaleOrdeDestinations = new HashSet<SaleOrdeDestination>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> OriginProvince { get; set; }
        public string TaxRatePercentOrigin { get; set; }
        public Nullable<long> DestinationProvince { get; set; }
        public string TaxRatePercentDestination { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
    
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual Province Province { get; set; }
        public virtual Province Province1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrdeDestination> SaleOrdeDestinations { get; set; }
    }
}
