//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalContainerDetail
    {
        public long ID { get; set; }
        public string ContainerNo { get; set; }
        public string Weight { get; set; }
        public Nullable<long> ContainerPick { get; set; }
        public Nullable<long> ContainerDrop { get; set; }
        public string Vessel { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> ContainerTypeID { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
    
        public virtual ContainerType ContainerType { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
