//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalBiltyVehicleUnLoadingReporting
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> UnLoadingDate { get; set; }
        public Nullable<System.TimeSpan> UnLoadingTime { get; set; }
        public Nullable<System.DateTime> UnLoadingGateInDate { get; set; }
        public Nullable<System.TimeSpan> UnLoadingGateInTime { get; set; }
        public Nullable<System.DateTime> UnLoadingGateOutDate { get; set; }
        public Nullable<System.TimeSpan> UnLoadingGateOutTime { get; set; }
        public string UnLoadingTotalDays { get; set; }
        public string UnLoadingTotalTime { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
    
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
