//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalBiltyDamageDetail
    {
        public long ID { get; set; }
        public Nullable<long> ProductItemID { get; set; }
        public Nullable<long> DamageTypeID { get; set; }
        public Nullable<long> DocumentTypeID { get; set; }
        public string ClaimDamageCost { get; set; }
        public string CauseOfDamage { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
    
        public virtual DamageType DamageType { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Product Product { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
