//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniversalChallan()
        {
            this.UniversalCheckBilties = new HashSet<UniversalCheckBilty>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public long ChallanNo { get; set; }
        public string ChallanManualNo { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string ExternalVehicleNo { get; set; }
        public Nullable<long> PickLocationID { get; set; }
        public Nullable<long> DropLocationID { get; set; }
        public Nullable<long> DriverID { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual PickLocation PickLocation { get; set; }
        public virtual PickLocation PickLocation1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniversalCheckBilty> UniversalCheckBilties { get; set; }
    }
}
