//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalBiltyContainerInformation
    {
        public long ID { get; set; }
        public Nullable<long> ContainerID { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<double> TotalQty { get; set; }
        public Nullable<double> GrandTotal { get; set; }
    
        public virtual ContainerType ContainerType { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
