//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalBiltyLocationInformation
    {
        public long ID { get; set; }
        public Nullable<long> LocationCode { get; set; }
        public Nullable<long> DropLocationCode { get; set; }
        public Nullable<bool> LocalPickStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
        public Nullable<bool> LocalDropStatus { get; set; }
        public Nullable<long> LocalPickCity { get; set; }
        public Nullable<long> LocalPickArea { get; set; }
        public string LocalPickAddress { get; set; }
        public Nullable<long> LocalDropCity { get; set; }
        public Nullable<long> LocalDropArea { get; set; }
        public string LocalDropAddress { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual PickLocation PickLocation { get; set; }
        public virtual PickLocation PickLocation1 { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
