//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalBiltyFreightDetail
    {
        public long ID { get; set; }
        public Nullable<double> AdditionalFrieght { get; set; }
        public Nullable<double> Labour { get; set; }
        public Nullable<double> Weighbridge { get; set; }
        public Nullable<double> Freight { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
    
        public virtual UniversalBilty UniversalBilty { get; set; }
    }
}
