//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalVehicleDetail
    {
        public long ID { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public string DriverName { get; set; }
        public string FatherName { get; set; }
        public string Cell { get; set; }
        public string NIC { get; set; }
        public string License { get; set; }
        public string Broker { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> UniversalBiltyID { get; set; }
        public string RegNo { get; set; }
    
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual UniversalBilty UniversalBilty { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
