//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssignedCompany
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> OwnCompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
